# this is an example file for what could be checked in to the cloud config repository for running locally (testing)
spring:
  application:
    name: spyglass

server:
  port: 8082

eureka:
  instance:
    hostname:
      localhost
  client:
    serviceUrl:
      defaultZone: "http://localhost:8082/eureka/"
    register-with-eureka: false
    fetch-registry: false
